import { Inter } from "next/font/google";
import "./globals.css";
import ToastComponent from "@/src/components/ToastComponent";
import Provider from "@/src/components/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: " Next-Auth App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}><Provider><ToastComponent />{children}</Provider></body>
    </html>
  );
}
